function [] = parsave(...
    outputFile,...
    nn,options,...
    TrainingSetImages,TrainingSetLabels,TestSetImages,TestSetLabels,...
    E_data,norm_gradient_data)

%Typically you cannot call 'save' inside a parfor loop.  As such, we need
%to use a separate function to enable saving within a parfor loop

save(outputFile,...
    'nn','options',...
    'TrainingSetImages','TrainingSetLabels','TestSetImages','TestSetLabels',...
    'E_data','norm_gradient_data')